# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3857bd7671c4b8b048db338d9841c021d03b589b8574f0f175e57fa54537bfce6f1dbd5033d6650c1f97af6ed9d037730b740d226c2e540569941c69a91ef6a

test:
  secret_key_base: 4eb632eda8d2b9498dbbf0003d5b8e8211ae8a68ef2e5a23aa66a60d1414859a4e8120a7471ef367627801f133521b9a577f3b49bfabcbacde4103ca8ca45aa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
